### ISSUE TITLE
Add Proxy in Ha

### ISSUE THREAD

**Issue by SoroushImanian** [Musixal/HAProxy#4]
سلام وقت بخیر
من از یک اسکریپت Ha دیگه استفاده میکردم که از Ha Proxy استفاده میکرد و Enable اش میکرد و باید تو پنل x-ui - پروکسی(Proxy Protocol) رو فعال کرد تا ست شه 

خواستم بدونم شما هم این قابلیت رو براش اضافه میکنید؟

**Comment by Musixal** [comment]
سلام. خیر
